steps:
  tmsUpload:
    credentialsId:	yes		
    customDescription:	no		
    mtaPath:	yes		
    mtaVersion:	no	*	
    nodeExtDescriptorMapping:	no		
    nodeName:	yes		
    proxy:	no		
    script:	yes		
    stashContent:	no	[buildResult]	
    useGoStep:	no		true, false
    verbose:	no		true, false
